/**
 * Shared text-quality checks used across generation and browser-automation
 * code. Kept in its own module (not contentAgentNew.ts) so that
 * browser/chatgpt/promptRunner.ts can import it without creating a circular
 * dependency (contentAgentNew.ts dynamically imports promptRunner.ts).
 */
export function isRefusal(text: string): boolean {
  // Normalize curly apostrophes (’) to straight ones so "I'm sorry"/"I can't"
  // still match regardless of which quote style the model used.
  const t = text.trim().toLowerCase().replace(/[’‘]/g, "'");
  return (
    t.startsWith("i'm sorry") ||
    t.startsWith("i am sorry") ||
    t.startsWith("i cannot") ||
    t.startsWith("i can't") ||
    t.startsWith("i'm unable") ||
    t.startsWith("i am unable") ||
    t.startsWith("unfortunately") ||
    t.startsWith("to generate this accurately") ||
    t.startsWith("to accurately generate") ||
    t.includes("cannot complete this request") ||
    t.includes("can't complete this request") ||
    t.includes("does not contain any concrete") ||
    t.includes("no concrete numbers") ||
    t.includes("as specified because") ||
    t.includes("i need the ken research") ||
    t.includes("i don't have access to") ||
    t.includes("i do not have access to") ||
    t.includes("please provide") ||
    t.includes("please share") ||
    t.includes("would require me to guess") ||
    t.includes("would require me to invent") ||
    t.length < 100
  );
}

// Special/control tokens some models (especially smaller NVIDIA NIM fallback
// models) leak into their raw completion text on a decoding glitch — e.g. a
// response that's just "<pad><pad><pad>...<pad>" repeated hundreds of times,
// or a stray <s>/</s>/<unk>/<eos>/[PAD]/<|endoftext|> wrapper around otherwise
// fine text. These are never meant to reach a real post, so strip them
// unconditionally before any text generated by callLLM() is used.
const MODEL_ARTIFACT_RE = /<pad>|<\/?s>|<unk>|<\/?eos>|<\/?bos>|\[PAD\]|<\|endoftext\|>|<\|pad\|>/gi;

export function stripModelArtifacts(text: string): string {
  return text.replace(MODEL_ARTIFACT_RE, '').replace(/\s{2,}/g, ' ').trim();
}

/**
 * True if a completion is unusable after stripping artifacts — either
 * nothing meaningful is left, or the raw response was mostly padding/junk
 * tokens to begin with (a strong signal the provider glitched rather than
 * genuinely returned a short real answer). Callers should treat this the
 * same as a failed request and rotate to the next key/model rather than
 * posting the leftover fragment.
 */
export function isDegenerate(rawText: string): boolean {
  const cleaned = stripModelArtifacts(rawText);
  if (cleaned.length < 10) return true;
  // If artifact-stripping removed more than half the original length, the
  // response was dominated by junk tokens even if a few real words survived.
  return cleaned.length < rawText.trim().length * 0.5;
}

// Some "reasoning" models (nemotron-3-nano-30b-a3b, nemotron-3-super-120b-a12b,
// and similar) occasionally answer with their raw chain-of-thought instead of
// just the final text — e.g. "We need to produce a caption meeting many
// constraints. First step: extract market name..." A quick single-word smoke
// test won't reveal this (there's nothing to reason about), but real prompts
// with several constraints can trigger it. Catch it by pattern rather than by
// blocklisting whole models, since the same model returns clean output most
// of the time.
const REASONING_LEAK_RE = /^(we need to|let'?s (think|analyze|produce|write)|first,? (step|let'?s)?|okay,? (so|the user|let'?s)|(the )?user (asks|wants|is asking|says|wrote|provided|has (asked|said))|analyzing the (request|prompt)|here'?s (a |my )?thinking)/i;

// Some newer "thinking" models (Qwen3, etc.) wrap their chain-of-thought in
// explicit <think>...</think> tags rather than writing it in plain prose —
// caught live 2026-08-27: qwen/qwen3.6-27b returned "<think> Thinking
// Process: 1. Deconstruct..." for every single call, which the phrase-based
// REASONING_LEAK_RE never matches since the response literally starts with a
// tag, not one of the phrases it looks for.
const THINK_TAG_RE = /<\/?think>/i;

export function isReasoningLeak(text: string): boolean {
  const t = text.trim();
  if (THINK_TAG_RE.test(t)) return true;
  if (REASONING_LEAK_RE.test(t)) return true;
  // Long internal-monologue responses tend to be dense with meta-commentary
  // markers ("so we should", "let's see", "note:", parenthetical asides) —
  // a real post almost never contains more than one of these.
  const markers = (t.match(/\b(so we (should|must|need to|will)|must (output|ensure)|let'?s see|note:|actually,|however,? maybe|possibly|probably|let'?s follow)\b/gi) || []).length;
  return markers >= 2;
}

// Distinctive section headers/labels that exist ONLY in our own prompt
// templates (contentAgentNew.ts), never in genuine post output. Some models
// occasionally echo a chunk of the instructions back instead of following
// them — this catches that regardless of which platform's prompt it came
// from, without needing the original prompt text at the call site.
const PROMPT_ECHO_MARKERS = [
  'STRICT RULES', 'OUTPUT RULES', 'FORMAT RULES', 'CTA RULES', 'SPACING RULES',
  'POST STRUCTURE', 'TONE AND STYLE', 'CHARACTER RULE', 'HARD LIMIT',
  'APPROVED CTA VARIATIONS', 'POWER PHRASES', 'MARKET VALUE (from sheet)',
  'REAL MARKET DATA', 'PREVIOUSLY POSTED TWEETS', 'Output ONLY the',
  'STEP 1 –', 'STEP 2 –', 'You are a market insights social media writer',
  'You are a professional B2B content writer', 'HASHTAGS (6-10)',
];

export function isPromptEcho(text: string): boolean {
  return PROMPT_ECHO_MARKERS.some(marker => text.includes(marker));
}

// Some free/fallback models are themselves moderation/safety classifiers
// (e.g. Llama-Guard-style) rather than general chat models, and instead of
// writing a post they return their classification verdict — "User Safety:
// safe", a bare "safe"/"unsafe", or a category code like "S1"/"S12". None
// of these are ever legitimate post content.
const SAFETY_LABEL_RE = /\b(user|bot|assistant|response)?\s*safety\s*:\s*(safe|unsafe)\b/i;
const SAFETY_ONLY_RE = /^\s*(safe|unsafe)\.?\s*$/i;
const SAFETY_CATEGORY_RE = /\bS(1[0-4]|[1-9])\b[\s,.:-]{0,20}(safe|unsafe)\b|\b(safe|unsafe)\b[\s,.:-]{0,20}\bS(1[0-4]|[1-9])\b/i;

export function isSafetyClassifierLeak(text: string): boolean {
  const t = text.trim();
  return (
    SAFETY_LABEL_RE.test(t) ||
    SAFETY_ONLY_RE.test(t) ||
    SAFETY_CATEGORY_RE.test(t) ||
    /content\s*polic(y|ies)\s*violation/i.test(t) ||
    /^\s*(category|classification)\s*:/i.test(t)
  );
}
