/**
 * contentAgentNew.ts — Content Generation Agent (Claude AI Loop)
 * Generates platform-specific posts from a single URL
 */

import Anthropic from '@anthropic-ai/sdk';
import { CONTENT_TOOLS, executeContentTool } from '../tools/contentTools.js';
import type { MessageParam } from '@anthropic-ai/sdk/resources/messages.js';
import type { SheetRow, BatchContext } from '../sheets/sheets.js';

const MODEL = 'claude-opus-4-1';
const MAX_TOOL_CALLS = 15;

export interface ContentResult {
  tweet: string;
  fbPost: string;
  liPost: string;
  blog: string;
  seoScore: number;
  sanityIssues: string[];
}

/**
 * Run content generation via Claude AI
 */
export async function runContentAgent(params: {
  url: string;
  title: string;
  seoRanking: number;
  priority: string;
  marketValue?: string;
  row?: SheetRow;
  batchCtx?: BatchContext;
}): Promise<ContentResult> {
  const client = new Anthropic({
    apiKey: process.env.ANTHROPIC_API_KEY,
  });

  const systemPrompt = `You are a content generation agent for Ken Research market reports.

Generate 4 distinct posts for the given report URL:
1. Tweet (280 chars max, X-optimized)
2. Facebook post (conversational, emoji-friendly)
3. LinkedIn post (professional, B2B tone)
4. Blog post (600-800 words, in-depth)

Steps:
1. Call generate_tweet to create the tweet
2. Call run_sanity_check on the tweet - if invalid, regenerate (max 3 times)
3. Call generate_facebook_post for FB
4. Call generate_linkedin_post for LI
5. Call generate_blog_post for blog
6. Compile all results and return as JSON with fields: tweet, fbPost, liPost, blog

All posts must be distinct (not just rephrasing the same text) and platform-optimized.`;

  const rowJson = params.row ? JSON.stringify(params.row) : '{}';
  const batchCtxJson = params.batchCtx
    ? JSON.stringify({
        seenUrls: Array.from(params.batchCtx.seenUrls),
        seenTexts: params.batchCtx.seenTexts,
      })
    : undefined;

  const userPrompt = `Generate social media content for this Ken Research report:
URL: ${params.url}
Title: ${params.title}
Priority: ${params.priority} (ranking page: ${params.seoRanking})
Market Value: ${params.marketValue || '(not specified)'}

Create distinct, platform-optimized posts.`;

  let messages: MessageParam[] = [
    { role: 'user', content: userPrompt },
  ];

  let toolCallCount = 0;
  const collectedResults: Partial<ContentResult> = {};

  while (toolCallCount < MAX_TOOL_CALLS) {
    const response = await client.messages.create({
      model: MODEL,
      max_tokens: 4096,
      system: systemPrompt,
      tools: CONTENT_TOOLS,
      messages,
    });

    // Check for final response with JSON
    const textContent = response.content.find(b => b.type === 'text');
    if (textContent && textContent.type === 'text') {
      const jsonMatch = textContent.text.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        try {
          const parsed = JSON.parse(jsonMatch[0]);
          return {
            tweet: parsed.tweet || collectedResults.tweet || '',
            fbPost: parsed.fbPost || collectedResults.fbPost || '',
            liPost: parsed.liPost || collectedResults.liPost || '',
            blog: parsed.blog || collectedResults.blog || '',
            seoScore: parsed.seoScore || collectedResults.seoScore || 75,
            sanityIssues: parsed.sanityIssues || collectedResults.sanityIssues || [],
          };
        } catch (e) {
          // Not valid JSON, continue
        }
      }
    }

    if (response.stop_reason === 'end_turn' || response.stop_reason === 'stop_sequence') {
      // If we have collected results, return them
      if (collectedResults.tweet || collectedResults.fbPost || collectedResults.liPost || collectedResults.blog) {
        return {
          tweet: collectedResults.tweet || '',
          fbPost: collectedResults.fbPost || '',
          liPost: collectedResults.liPost || '',
          blog: collectedResults.blog || '',
          seoScore: collectedResults.seoScore || 75,
          sanityIssues: collectedResults.sanityIssues || [],
        };
      }
      // Otherwise, try to parse from text content
      if (textContent && textContent.type === 'text') {
        return parseContentResult(response.content);
      }
      throw new Error('No content generated by agent');
    }

    const toolUses = response.content.filter(b => b.type === 'tool_use');
    if (toolUses.length === 0) {
      if (textContent && textContent.type === 'text') {
        return parseContentResult(response.content);
      }
      throw new Error('Agent did not call any tools and did not return content');
    }

    messages.push({
      role: 'assistant',
      content: response.content,
    });

    toolCallCount += toolUses.length;

    // Execute tools and collect results
    const toolResults = await Promise.all(
      toolUses.map(async (tu) => {
        const result = await executeContentTool(tu.name, {
          ...tu.input as Record<string, any>,
          rowJson,
          batchCtxJson,
        });

        // Collect individual results
        if (result.tweet) collectedResults.tweet = result.tweet;
        if (result.fbPost) collectedResults.fbPost = result.fbPost;
        if (result.liPost) collectedResults.liPost = result.liPost;
        if (result.blog) collectedResults.blog = result.blog;
        if (result.sanityIssues) collectedResults.sanityIssues = result.sanityIssues;

        return {
          type: 'tool_result' as const,
          tool_use_id: tu.id,
          content: JSON.stringify(result),
        };
      }),
    );

    messages.push({
      role: 'user',
      content: toolResults,
    });
  }

  // If we reached max tool calls but have collected results, return them
  if (collectedResults.tweet || collectedResults.fbPost || collectedResults.liPost || collectedResults.blog) {
    return {
      tweet: collectedResults.tweet || '',
      fbPost: collectedResults.fbPost || '',
      liPost: collectedResults.liPost || '',
      blog: collectedResults.blog || '',
      seoScore: collectedResults.seoScore || 75,
      sanityIssues: collectedResults.sanityIssues || [],
    };
  }

  throw new Error('Content generation exceeded max tool calls without producing content');
}

/**
 * Parse content result from Claude response
 */
function parseContentResult(content: any[]): ContentResult {
  const textContent = content.find(b => b.type === 'text');
  if (!textContent || textContent.type !== 'text') {
    throw new Error('No text response from content agent');
  }

  const text = textContent.text;
  const jsonMatch = text.match(/\{[\s\S]*\}/);
  if (!jsonMatch) {
    throw new Error('Could not parse JSON from content agent response');
  }

  const parsed = JSON.parse(jsonMatch[0]);

  return {
    tweet: parsed.tweet || '',
    fbPost: parsed.fbPost || '',
    liPost: parsed.liPost || '',
    blog: parsed.blog || '',
    seoScore: parsed.seoScore || 75,
    sanityIssues: parsed.sanityIssues || [],
  };
}
