/**
 * testPoster.ts — Standalone poster tester for the 5 new platforms.
 * Logs in with a saved session, posts a small dummy test item, prints the
 * result URL. Isolates the fragile selector logic in poster.ts from content
 * generation and sheet wiring, so you can confirm posting actually works
 * before trusting a full batch run.
 *
 * Usage:
 *   npx tsx src/tools/testPoster.ts --platform instapaper --nickname pranav
 *   npx tsx src/tools/testPoster.ts --platform raindrop --nickname pranav
 *   npx tsx src/tools/testPoster.ts --platform mastodon --nickname pranav
 *   npx tsx src/tools/testPoster.ts --platform pdfhost --nickname pranav
 *   npx tsx src/tools/testPoster.ts --platform pearltrees --nickname pranav
 *   npx tsx src/tools/testPoster.ts --platform scribd --nickname pranav
 */
import 'dotenv/config';
import { htmlToPdf } from '../utils/contentConverter.js';

const TEST_TITLE = 'Ken Research Test Post — Global Widget Market';
const TEST_URL = 'https://www.kenresearch.com/blog/test-widget-market';
const TEST_HTML = `
  <h1>Global Widget Market</h1>
  <p>This is a test document generated by testPoster.ts to verify the posting
  flow end-to-end. The global widget market is projected to grow steadily
  through 2030, driven by rising demand across key regions.</p>
  <h2>Key Findings</h2>
  <p>Market size, growth drivers, and competitive landscape summary go here.</p>
`;

async function main() {
  const args = process.argv.slice(2);
  const platform = args[args.indexOf('--platform') + 1];
  const nickname = args[args.indexOf('--nickname') + 1] || 'pranav';

  if (!platform) {
    console.error('Usage: npx tsx src/tools/testPoster.ts --platform <instapaper|raindrop|mastodon|pdfhost|pearltrees> --nickname <name>');
    process.exit(1);
  }

  console.log(`\n🧪 Testing ${platform} poster (account: ${nickname})...\n`);

  try {
    switch (platform) {
      case 'instapaper': {
        const { loginToInstapaper, closeInstapaperBrowser } = await import('../browser/instapaper/login.js');
        const { postToInstapaper } = await import('../browser/instapaper/poster.js');
        const page = await loginToInstapaper({ nickname });
        const result = await postToInstapaper(page, TEST_TITLE, TEST_URL, 'Test note from testPoster.ts');
        console.log('\n✅ RESULT:', result);
        await closeInstapaperBrowser();
        break;
      }
      case 'raindrop': {
        const { loginToRaindrop, closeRaindropBrowser } = await import('../browser/raindrop/login.js');
        const { postToRaindrop } = await import('../browser/raindrop/poster.js');
        const page = await loginToRaindrop({ nickname });
        const result = await postToRaindrop(page, TEST_TITLE, TEST_URL, 'Test note from testPoster.ts', ['test', 'ken-research']);
        console.log('\n✅ RESULT:', result);
        await closeRaindropBrowser();
        break;
      }
      case 'mastodon': {
        const { loginToMastodon, closeMastodonBrowser } = await import('../browser/mastodon/login.js');
        const { postToMastodon } = await import('../browser/mastodon/poster.js');
        const page = await loginToMastodon({ nickname });
        const result = await postToMastodon(page, `${TEST_TITLE} — test toot from testPoster.ts ${TEST_URL}`);
        console.log('\n✅ RESULT:', result);
        await closeMastodonBrowser();
        break;
      }
      case 'pdfhost': {
        const { loginToPdfHost, closePdfHostBrowser } = await import('../browser/pdfhost/login.js');
        const { postToPdfHost } = await import('../browser/pdfhost/poster.js');
        console.log('   Generating test PDF...');
        const pdfPath = await htmlToPdf(TEST_HTML, 'test-widget-market', 999999);
        console.log(`   PDF built: ${pdfPath}`);
        const page = await loginToPdfHost({ nickname });
        const result = await postToPdfHost(page, pdfPath, TEST_TITLE, 'Test description from testPoster.ts');
        console.log('\n✅ RESULT:', result);
        await closePdfHostBrowser();
        break;
      }
      case 'pearltrees': {
        const { loginToPearltrees, closePearltreesBrowser } = await import('../browser/pearltrees/login.js');
        const { postToPearltrees } = await import('../browser/pearltrees/poster.js');
        const page = await loginToPearltrees({ nickname });
        const result = await postToPearltrees(page, TEST_TITLE, TEST_URL);
        console.log('\n✅ RESULT:', result);
        await closePearltreesBrowser();
        break;
      }
      case 'scribd': {
        const { loginToScribd, closeScribdBrowser } = await import('../browser/scribd/login.js');
        const { postToScribd } = await import('../browser/scribd/poster.js');
        console.log('   Generating test PDF...');
        const pdfPath = await htmlToPdf(TEST_HTML, 'test-widget-market', 999999);
        console.log(`   PDF built: ${pdfPath}`);
        const page = await loginToScribd({ nickname });
        const result = await postToScribd(page, pdfPath, TEST_TITLE, TEST_URL);
        console.log('\n✅ RESULT:', result);
        await closeScribdBrowser();
        break;
      }
      default:
        console.error(`Unknown platform "${platform}"`);
        process.exit(1);
    }
    console.log('\n🎉 Test post succeeded — check the platform to confirm it looks right.\n');
    process.exit(0);
  } catch (err: any) {
    console.error(`\n❌ Test post FAILED: ${err.message}\n`);
    console.error(err.stack);
    process.exit(1);
  }
}

main();
